{
 "title": "Node Exporter",
 "tags": [ "linux" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "query": {
     "query": "label_values(asserts:mixin_pod_workload, asserts_env)"
    }
   },
   {
    "name": "site",
    "query": {
     "query": "label_values(asserts:mixin_pod_workload{asserts_env=~\"$env\"}, asserts_site)"
    }
   },
   { "name": "ds", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info{asserts_env=~\"$env\",asserts_site=~\"$site\"}, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{asserts_env=~\"$env\",asserts_site=~\"$site\",job=\"$job\"}, instance)"
    }
   },
   { "name": "diskdevices", "query": "[a-z]+|nvme[0-9]+n[0-9]+" }
  ]
 },
 "panels": [
  { "title": "Quick CPU / Mem / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",mode='idle',instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"} - node_memory_SwapFree_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"} )) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"} - node_boot_time_seconds{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",mode=\"system\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",mode='user',instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",mode='iowait',instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",mode=~\".*irq\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",mode='idle',instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"} - node_memory_MemFree_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"} - (node_memory_Cached_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"} + node_memory_Buffers_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"} + node_memory_Buffers_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"} - node_memory_SwapFree_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "CPU / Memory / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",mode=\"system\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",mode='user',instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",mode='nice',instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",mode='idle',instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Idle - Waiting for something to happen"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",mode='iowait',instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",mode='irq',instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",mode='softirq',instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",mode='steal',instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",mode='guest',instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"} - node_memory_MemFree_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"} - node_memory_Buffers_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"} - node_memory_Cached_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"} - node_memory_Slab_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"} - node_memory_PageTables_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"} - node_memory_SwapCached_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "Unused - Free memory unassigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"} - node_memory_SwapFree_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\",device!~'rootfs'} - node_filesystem_avail_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully written bytes"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\",device=~\"$diskdevices\"} [$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Memory Meminfo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Memory Active / Inactive",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "node_memory_Inactive_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "Inactive - Memory which has been less recently used.  It is more eligible to be reclaimed for other purposes"
    },
    {
     "expr": "node_memory_Active_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "Active - Memory that has been used more recently and usually not reclaimed unless absolutely necessary"
    }
   ]
  },
  {
   "title": "Memory Commited",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "node_memory_Committed_AS_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "Committed_AS - Amount of memory presently allocated on the system"
    },
    {
     "expr": "node_memory_CommitLimit_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "CommitLimit - Amount of  memory currently available to be allocated on the system"
    }
   ]
  },
  {
   "title": "Memory Active / Inactive Detail",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "node_memory_Inactive_file_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "Inactive_file - File-backed memory on inactive LRU list"
    },
    {
     "expr": "node_memory_Inactive_anon_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "Inactive_anon - Anonymous and swap cache on inactive LRU list, including tmpfs (shmem)"
    },
    {
     "expr": "node_memory_Active_file_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "Active_file - File-backed memory on active LRU list"
    },
    {
     "expr": "node_memory_Active_anon_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "Active_anon - Anonymous and swap cache on active least-recently-used (LRU) list, including tmpfs"
    }
   ]
  },
  {
   "title": "Memory Writeback and Dirty",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "node_memory_Writeback_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "Writeback - Memory which is actively being written back to disk"
    },
    {
     "expr": "node_memory_WritebackTmp_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "WritebackTmp - Memory used by FUSE for temporary writeback buffers"
    },
    {
     "expr": "node_memory_Dirty_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "Dirty - Memory which is waiting to get written back to the disk"
    }
   ]
  },
  {
   "title": "Memory Shared and Mapped",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "node_memory_Mapped_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "Mapped - Used memory in mapped pages files which have been mmaped, such as libraries"
    },
    {
     "expr": "node_memory_Shmem_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "Shmem - Used shared memory (shared between several processes, thus including RAM disks)"
    },
    {
     "expr": "node_memory_ShmemHugePages_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "ShmemHugePages - Memory used by shared memory (shmem) and tmpfs allocated  with huge pages"
    },
    {
     "expr": "node_memory_ShmemPmdMapped_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "ShmemPmdMapped - Ammount of shared (shmem/tmpfs) memory backed by huge pages"
    }
   ]
  },
  {
   "title": "Memory Slab",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "node_memory_SUnreclaim_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "SUnreclaim - Part of Slab, that cannot be reclaimed on memory pressure"
    },
    {
     "expr": "node_memory_SReclaimable_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "SReclaimable - Part of Slab, that might be reclaimed, such as caches"
    }
   ]
  },
  {
   "title": "Memory Vmalloc",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "node_memory_VmallocChunk_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "VmallocChunk - Largest contigious block of vmalloc area which is free"
    },
    {
     "expr": "node_memory_VmallocTotal_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "VmallocTotal - Total size of vmalloc memory area"
    },
    {
     "expr": "node_memory_VmallocUsed_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "VmallocUsed - Amount of vmalloc area which is used"
    }
   ]
  },
  {
   "title": "Memory Bounce",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 100 },
   "targets": [
    {
     "expr": "node_memory_Bounce_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "Bounce - Memory used for block device bounce buffers"
    }
   ]
  },
  {
   "title": "Memory Anonymous",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "node_memory_AnonHugePages_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "AnonHugePages - Memory in anonymous huge pages"
    },
    {
     "expr": "node_memory_AnonPages_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "AnonPages - Memory in user pages not backed by files"
    }
   ]
  },
  {
   "title": "Memory Kernel / CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 110 },
   "targets": [
    {
     "expr": "node_memory_KernelStack_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "KernelStack - Kernel memory stack. This is not reclaimable"
    },
    {
     "expr": "node_memory_Percpu_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "PerCPU - Per CPU memory allocated dynamically by loadable modules"
    }
   ]
  },
  {
   "title": "Memory HugePages Counter",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 120 },
   "targets": [
    {
     "expr": "node_memory_HugePages_Free{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "HugePages_Free - Huge pages in the pool that are not yet allocated"
    },
    {
     "expr": "node_memory_HugePages_Rsvd{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "HugePages_Rsvd - Huge pages for which a commitment to allocate from the pool has been made, but no allocation has yet been made"
    },
    {
     "expr": "node_memory_HugePages_Surp{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "HugePages_Surp - Huge pages in the pool above the value in /proc/sys/vm/nr_hugepages"
    }
   ]
  },
  {
   "title": "Memory HugePages Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 120 },
   "targets": [
    {
     "expr": "node_memory_HugePages_Total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "HugePages - Total size of the pool of huge pages"
    },
    {
     "expr": "node_memory_Hugepagesize_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "Hugepagesize - Huge Page size"
    }
   ]
  },
  {
   "title": "Memory DirectMap",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 130 },
   "targets": [
    {
     "expr": "node_memory_DirectMap1G_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "DirectMap1G - Amount of pages mapped as this size"
    },
    {
     "expr": "node_memory_DirectMap2M_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "DirectMap2M - Amount of pages mapped as this size"
    },
    {
     "expr": "node_memory_DirectMap4k_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "DirectMap4K - Amount of pages mapped as this size"
    }
   ]
  },
  {
   "title": "Memory Unevictable and MLocked",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 130 },
   "targets": [
    {
     "expr": "node_memory_Unevictable_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "Unevictable - Amount of unevictable memory that can't be swapped out for a variety of reasons"
    },
    {
     "expr": "node_memory_Mlocked_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "MLocked - Size of pages locked to memory using the mlock() system call"
    }
   ]
  },
  {
   "title": "Memory NFS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 140 },
   "targets": [
    {
     "expr": "node_memory_NFS_Unstable_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
     "legendFormat": "NFS Unstable - Memory in NFS pages sent to the server, but not yet commited to the storage"
    }
   ]
  },
  {
   "title": "Memory Vmstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Pages In / Out",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 445 },
     "targets": [
      {
       "expr": "rate(node_vmstat_pgpgin{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Pagesin - Page in operations"
      },
      {
       "expr": "rate(node_vmstat_pgpgout{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Pagesout - Page out operations"
      }
     ]
    },
    {
     "title": "Memory Pages Swap In / Out",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 445 },
     "targets": [
      {
       "expr": "rate(node_vmstat_pswpin{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Pswpin - Pages swapped in"
      },
      {
       "expr": "rate(node_vmstat_pswpout{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Pswpout - Pages swapped out"
      }
     ]
    },
    {
     "title": "Memory Page Faults",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 651 },
     "targets": [
      {
       "expr": "rate(node_vmstat_pgfault{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Pgfault - Page major and minor fault operations"
      },
      {
       "expr": "rate(node_vmstat_pgmajfault{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Pgmajfault - Major page fault operations"
      },
      {
       "expr": "rate(node_vmstat_pgfault{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])  - rate(node_vmstat_pgmajfault{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Pgminfault - Minor page fault operations"
      }
     ]
    },
    {
     "title": "OOM Killer",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 651 },
     "targets": [
      {
       "expr": "rate(node_vmstat_oom_kill{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "oom killer invocations "
      }
     ]
    }
   ]
  },
  {
   "title": "System Timesync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 151 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time Syncronized Drift",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 446 },
     "targets": [
      {
       "expr": "node_timex_estimated_error_seconds{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "Estimated error in seconds"
      },
      {
       "expr": "node_timex_offset_seconds{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "Time offset in between local system and reference clock"
      },
      {
       "expr": "node_timex_maxerror_seconds{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "Maximum error in seconds"
      }
     ]
    },
    {
     "title": "Time PLL Adjust",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 446 },
     "targets": [
      {
       "expr": "node_timex_loop_time_constant{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "Phase-locked loop time adjust"
      }
     ]
    },
    {
     "title": "Time Syncronized Status",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 652 },
     "targets": [
      {
       "expr": "node_timex_sync_status{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "Is clock synchronized to a reliable server (1 = yes, 0 = no)"
      },
      {
       "expr": "node_timex_frequency_adjustment_ratio{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "Local clock frequency adjustment"
      }
     ]
    },
    {
     "title": "Time Misc",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 652 },
     "targets": [
      {
       "expr": "node_timex_tick_seconds{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "Seconds between clock ticks"
      },
      {
       "expr": "node_timex_tai_offset_seconds{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "International Atomic Time (TAI) offset"
      }
     ]
    }
   ]
  },
  {
   "title": "System Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 152 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes Status",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 381 },
     "targets": [
      {
       "expr": "node_procs_blocked{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "Processes blocked waiting for I/O to complete"
      },
      {
       "expr": "node_procs_running{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "Processes in runnable state"
      }
     ]
    },
    {
     "title": "Processes State",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 381 },
     "targets": [
      {
       "expr": "node_processes_state{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "{{ state }}"
      }
     ]
    },
    {
     "title": "Processes  Forks",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 391 },
     "targets": [
      {
       "expr": "rate(node_forks_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Processes forks second"
      }
     ]
    },
    {
     "title": "Processes Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 391 },
     "targets": [
      {
       "expr": "rate(process_virtual_memory_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Processes virtual memory size in bytes"
      },
      {
       "expr": "process_resident_memory_max_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "Maximum amount of virtual memory available in bytes"
      },
      {
       "expr": "rate(process_virtual_memory_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Processes virtual memory size in bytes"
      },
      {
       "expr": "rate(process_virtual_memory_max_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Maximum amount of virtual memory available in bytes"
      }
     ]
    },
    {
     "title": "PIDs Number and Limit",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 449 },
     "targets": [
      {
       "expr": "node_processes_pids{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "Number of PIDs"
      },
      {
       "expr": "node_processes_max_processes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "PIDs limit"
      }
     ]
    },
    {
     "title": "Process schedule stats Running / Waiting",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 449 },
     "targets": [
      {
       "expr": "rate(node_schedstat_running_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "CPU {{ cpu }} - seconds spent running a process"
      },
      {
       "expr": "rate(node_schedstat_waiting_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "CPU {{ cpu }} - seconds spent by processing waiting for this CPU"
      }
     ]
    },
    {
     "title": "Threads Number and Limit",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 655 },
     "targets": [
      {
       "expr": "node_processes_threads{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "Allocated threads"
      },
      {
       "expr": "node_processes_max_threads{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "Threads limit"
      }
     ]
    }
   ]
  },
  {
   "title": "System Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 },
   "collapsed": true,
   "panels": [
    {
     "title": "Context Switches / Interrupts",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 448 },
     "targets": [
      {
       "expr": "rate(node_context_switches_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Context switches"
      },
      {
       "expr": "rate(node_intr_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Interrupts"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 448 },
     "targets": [
      {
       "expr": "node_load1{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "node_load5{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "node_load15{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "Load 15m"
      }
     ]
    },
    {
     "title": "Interrupts Detail",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 654 },
     "targets": [
      {
       "expr": "rate(node_interrupts_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ type }} - {{ info }}"
      }
     ]
    },
    {
     "title": "Schedule timeslices executed by each cpu",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 654 },
     "targets": [
      {
       "expr": "rate(node_schedstat_timeslices_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "CPU {{ cpu }}"
      }
     ]
    },
    {
     "title": "Entropy",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 664 },
     "targets": [
      {
       "expr": "node_entropy_available_bits{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "Entropy available to random number generators"
      }
     ]
    },
    {
     "title": "CPU time spent in user and system contexts",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 664 },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Time spent"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 674 },
     "targets": [
      {
       "expr": "process_max_fds{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "Maximum open file descriptors"
      },
      {
       "expr": "process_open_fds{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "Open file descriptors"
      }
     ]
    }
   ]
  },
  {
   "title": "Hardware Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hardware temperature monitor",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 449 },
     "targets": [
      {
       "expr": "node_hwmon_temp_celsius{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "{{ chip }} {{ sensor }} temp"
      },
      {
       "expr": "node_hwmon_temp_crit_celsius{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "{{ chip }} {{ sensor }} Critical"
      }
     ]
    },
    {
     "title": "Throttle cooling device",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 449 },
     "targets": [
      {
       "expr": "node_cooling_device_cur_state{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "Current {{ name }} in {{ type }}"
      },
      {
       "expr": "node_cooling_device_max_state{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "Max {{ name }} in {{ type }}"
      }
     ]
    },
    {
     "title": "Power supply",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 655 },
     "targets": [
      {
       "expr": "node_power_supply_online{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "{{ power_supply }} online"
      }
     ]
    }
   ]
  },
  {
   "title": "Systemd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 155 },
   "collapsed": true,
   "panels": [
    {
     "title": "Systemd Sockets",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 450 },
     "targets": [
      {
       "expr": "rate(node_systemd_socket_accepted_connections_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{ name }} Connections"
      }
     ]
    },
    {
     "title": "Systemd Units State",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 450 },
     "targets": [
      {
       "expr": "node_systemd_units{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\",state=\"activating\"}",
       "legendFormat": "Activating"
      },
      {
       "expr": "node_systemd_units{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\",state=\"active\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "node_systemd_units{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\",state=\"deactivating\"}",
       "legendFormat": "Deactivating"
      },
      {
       "expr": "node_systemd_units{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\",state=\"failed\"}",
       "legendFormat": "Failed"
      },
      {
       "expr": "node_systemd_units{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\",state=\"inactive\"}",
       "legendFormat": "Inactive"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 156 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk IOps Completed",
     "type": "timeseries",
     "description": "The number (after merges) of I/O requests completed per second for the device",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 451 },
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Reads completed"
      },
      {
       "expr": "rate(node_disk_writes_completed_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Writes completed"
      }
     ]
    },
    {
     "title": "Disk R/W Data",
     "type": "timeseries",
     "description": "The number of bytes read from or written to the device per second",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 451 },
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Read bytes"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Written bytes"
      }
     ]
    },
    {
     "title": "Disk Average Wait Time",
     "type": "timeseries",
     "description": "The average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 461 },
     "targets": [
      {
       "expr": "rate(node_disk_read_time_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval]) / rate(node_disk_reads_completed_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - r_await"
      },
      {
       "expr": "rate(node_disk_write_time_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval]) / rate(node_disk_writes_completed_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - w_await"
      }
     ]
    },
    {
     "title": "Average Queue Size",
     "type": "timeseries",
     "description": "The average queue length of the requests that were issued to the device",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 461 },
     "targets": [
      {
       "expr": "rate(node_disk_io_time_weighted_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk R/W Merged",
     "type": "timeseries",
     "description": "The number of read and write requests merged per second that were queued to the device",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 471 },
     "targets": [
      {
       "expr": "rate(node_disk_reads_merged_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Read merged"
      },
      {
       "expr": "rate(node_disk_writes_merged_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Write merged"
      }
     ]
    },
    {
     "title": "Time Spent Doing I/Os",
     "type": "timeseries",
     "description": "Percentage of elapsed time during which I/O requests were issued to the device (bandwidth utilization for the device). Device saturation occurs when this value is close to 100% for devices serving requests serially.  But for devices  serving requests in parallel, such as RAID arrays and modern SSDs, this number does not reflect their performance limits.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 471 },
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - IO"
      },
      {
       "expr": "rate(node_disk_discard_time_seconds_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - discard"
      }
     ]
    },
    {
     "title": "Instantaneous Queue Size",
     "type": "timeseries",
     "description": "The number of outstanding requests at the instant the sample was taken. Incremented as requests are given to appropriate struct request_queue and decremented as they finish.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 481 },
     "targets": [
      {
       "expr": "rate(node_disk_io_now{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - IO now"
      }
     ]
    },
    {
     "title": "Disk IOps Discards completed / merged",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 481 },
     "targets": [
      {
       "expr": "rate(node_disk_discards_completed_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Discards completed"
      },
      {
       "expr": "rate(node_disk_discards_merged_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Discards merged"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 157 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem space available",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 452 },
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - Available"
      }
     ]
    },
    {
     "title": "File Nodes Free",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 452 },
     "targets": [
      {
       "expr": "node_filesystem_files_free{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - Free file nodes"
      }
     ]
    },
    {
     "title": "File Descriptor",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 462 },
     "targets": [
      {
       "expr": "node_filefd_maximum{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "Max open files"
      },
      {
       "expr": "node_filefd_allocated{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "Open files"
      }
     ]
    },
    {
     "title": "File Nodes Size",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 462 },
     "targets": [
      {
       "expr": "node_filesystem_files{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - File nodes total"
      }
     ]
    },
    {
     "title": "Filesystem in ReadOnly / Error",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 472 },
     "targets": [
      {
       "expr": "node_filesystem_readonly{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - ReadOnly"
      },
      {
       "expr": "node_filesystem_device_error{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\",device!~'rootfs',fstype!~'tmpfs'}",
       "legendFormat": "{{mountpoint}} - Device error"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic by Packets",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 648 },
     "targets": [
      {
       "expr": "rate(node_network_receive_packets_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "rate(node_network_transmit_packets_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Traffic Errors",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 648 },
     "targets": [
      {
       "expr": "rate(node_network_receive_errs_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Receive errors"
      },
      {
       "expr": "rate(node_network_transmit_errs_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Rransmit errors"
      }
     ]
    },
    {
     "title": "Network Traffic Drop",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 658 },
     "targets": [
      {
       "expr": "rate(node_network_receive_drop_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Receive drop"
      },
      {
       "expr": "rate(node_network_transmit_drop_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Transmit drop"
      }
     ]
    },
    {
     "title": "Network Traffic Compressed",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 658 },
     "targets": [
      {
       "expr": "rate(node_network_receive_compressed_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Receive compressed"
      },
      {
       "expr": "rate(node_network_transmit_compressed_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Transmit compressed"
      }
     ]
    },
    {
     "title": "Network Traffic Multicast",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 668 },
     "targets": [
      {
       "expr": "rate(node_network_receive_multicast_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Receive multicast"
      }
     ]
    },
    {
     "title": "Network Traffic Fifo",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 668 },
     "targets": [
      {
       "expr": "rate(node_network_receive_fifo_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Receive fifo"
      },
      {
       "expr": "rate(node_network_transmit_fifo_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Transmit fifo"
      }
     ]
    },
    {
     "title": "Network Traffic Frame",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 678 },
     "targets": [
      {
       "expr": "rate(node_network_receive_frame_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Receive frame"
      }
     ]
    },
    {
     "title": "Network Traffic Carrier",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 678 },
     "targets": [
      {
       "expr": "rate(node_network_transmit_carrier_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Statistic transmit_carrier"
      }
     ]
    },
    {
     "title": "Network Traffic Colls",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 688 },
     "targets": [
      {
       "expr": "rate(node_network_transmit_colls_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Transmit colls"
      }
     ]
    },
    {
     "title": "NF Contrack",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 688 },
     "targets": [
      {
       "expr": "node_nf_conntrack_entries{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "NF conntrack entries"
      },
      {
       "expr": "node_nf_conntrack_entries_limit{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "NF conntrack limit"
      }
     ]
    },
    {
     "title": "ARP Entries",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 698 },
     "targets": [
      {
       "expr": "node_arp_entries{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "{{ device }} - ARP entries"
      }
     ]
    },
    {
     "title": "MTU",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 698 },
     "targets": [
      {
       "expr": "node_network_mtu_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "{{ device }} - Bytes"
      }
     ]
    },
    {
     "title": "Speed",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 708 },
     "targets": [
      {
       "expr": "node_network_speed_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "{{ device }} - Speed"
      }
     ]
    },
    {
     "title": "Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 708 },
     "targets": [
      {
       "expr": "node_network_transmit_queue_length{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "{{ device }} -   Interface transmit queue length"
      }
     ]
    },
    {
     "title": "Softnet Packets",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 718 },
     "targets": [
      {
       "expr": "rate(node_softnet_processed_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "CPU {{cpu}} - Processed"
      },
      {
       "expr": "rate(node_softnet_dropped_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "CPU {{cpu}} - Dropped"
      }
     ]
    },
    {
     "title": "Softnet Out of Quota",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 718 },
     "targets": [
      {
       "expr": "rate(node_softnet_times_squeezed_total{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "CPU {{cpu}} - Squeezed"
      }
     ]
    },
    {
     "title": "Network Operational Status",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 728 },
     "targets": [
      {
       "expr": "node_network_up{asserts_env=~\"$env\",asserts_site=~\"$site\",operstate=\"up\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "{{interface}} - Operational state UP"
      },
      {
       "expr": "node_network_carrier{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "{{device}} - Physical link state"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 159 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sockstat TCP",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 387 },
     "targets": [
      {
       "expr": "node_sockstat_TCP_alloc{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "TCP_alloc - Allocated sockets"
      },
      {
       "expr": "node_sockstat_TCP_inuse{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "TCP_inuse - Tcp sockets currently in use"
      },
      {
       "expr": "node_sockstat_TCP_orphan{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "TCP_orphan - Orphan sockets"
      },
      {
       "expr": "node_sockstat_TCP_tw{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "TCP_tw - Sockets wating close"
      }
     ]
    },
    {
     "title": "Sockstat UDP",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 387 },
     "targets": [
      {
       "expr": "node_sockstat_UDPLITE_inuse{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "UDPLITE_inuse - Udplite sockets currently in use"
      },
      {
       "expr": "node_sockstat_UDP_inuse{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "UDP_inuse - Udp sockets currently in use"
      },
      {
       "expr": "node_sockstat_UDP_mem{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "UDP_mem - Used memory for udp"
      }
     ]
    },
    {
     "title": "Sockstat Used",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 445 },
     "targets": [
      {
       "expr": "node_sockstat_sockets_used{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "Sockets_used - Sockets currently in use"
      }
     ]
    },
    {
     "title": "Sockstat Memory Size",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 445 },
     "targets": [
      {
       "expr": "node_sockstat_TCP_mem_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "mem_bytes - TCP sockets in that state"
      },
      {
       "expr": "node_sockstat_UDP_mem_bytes{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "mem_bytes - UDP sockets in that state"
      }
     ]
    },
    {
     "title": "Sockstat FRAG / RAW",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 651 },
     "targets": [
      {
       "expr": "node_sockstat_FRAG_inuse{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "FRAG_inuse - Frag sockets currently in use"
      },
      {
       "expr": "node_sockstat_FRAG_memory{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "FRAG_memory - Used memory for frag"
      },
      {
       "expr": "node_sockstat_RAW_inuse{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "RAW_inuse - Raw sockets currently in use"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Netstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 160 },
   "collapsed": true,
   "panels": [
    {
     "title": "Netstat IP In / Out Octets",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 650 },
     "targets": [
      {
       "expr": "rate(node_netstat_IpExt_InOctets{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "InOctets - Received octets"
      },
      {
       "expr": "rate(node_netstat_IpExt_OutOctets{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "OutOctets - Sent octets"
      }
     ]
    },
    {
     "title": "Netstat IP Forwarding",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 650 },
     "targets": [
      {
       "expr": "rate(node_netstat_Ip_Forwarding{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Forwarding - IP forwarding"
      }
     ]
    },
    {
     "title": "ICMP In / Out",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 660 },
     "targets": [
      {
       "expr": "rate(node_netstat_Icmp_InMsgs{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "InMsgs -  Messages which the entity received. Note that this counter includes all those counted by icmpInErrors"
      },
      {
       "expr": "rate(node_netstat_Icmp_OutMsgs{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "OutMsgs - Messages which this entity attempted to send. Note that this counter includes all those counted by icmpOutErrors"
      }
     ]
    },
    {
     "title": "ICMP Errors",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 660 },
     "targets": [
      {
       "expr": "rate(node_netstat_Icmp_InErrors{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "InErrors - Messages which the entity received but determined as having ICMP-specific errors (bad ICMP checksums, bad length, etc.)"
      }
     ]
    },
    {
     "title": "UDP In / Out",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 670 },
     "targets": [
      {
       "expr": "rate(node_netstat_Udp_InDatagrams{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "InDatagrams - Datagrams received"
      },
      {
       "expr": "rate(node_netstat_Udp_OutDatagrams{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "OutDatagrams - Datagrams sent"
      }
     ]
    },
    {
     "title": "UDP Errors",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 670 },
     "targets": [
      {
       "expr": "rate(node_netstat_Udp_InErrors{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "InErrors - UDP Datagrams that could not be delivered to an application"
      },
      {
       "expr": "rate(node_netstat_Udp_NoPorts{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "NoPorts - UDP Datagrams received on a port with no listener"
      },
      {
       "expr": "rate(node_netstat_UdpLite_InErrors{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "InErrors Lite - UDPLite Datagrams that could not be delivered to an application"
      },
      {
       "expr": "rate(node_netstat_Udp_RcvbufErrors{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "RcvbufErrors - UDP buffer errors received"
      },
      {
       "expr": "rate(node_netstat_Udp_SndbufErrors{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "SndbufErrors - UDP buffer errors send"
      }
     ]
    },
    {
     "title": "TCP In / Out",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 680 },
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_InSegs{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "InSegs - Segments received, including those received in error. This count includes segments received on currently established connections"
      },
      {
       "expr": "rate(node_netstat_Tcp_OutSegs{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "OutSegs - Segments sent, including those on current connections but excluding those containing only retransmitted octets"
      }
     ]
    },
    {
     "title": "TCP Errors",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 680 },
     "targets": [
      {
       "expr": "rate(node_netstat_TcpExt_ListenOverflows{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "ListenOverflows - Times the listen queue of a socket overflowed"
      },
      {
       "expr": "rate(node_netstat_TcpExt_ListenDrops{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "ListenDrops - SYNs to LISTEN sockets ignored"
      },
      {
       "expr": "rate(node_netstat_TcpExt_TCPSynRetrans{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "TCPSynRetrans - SYN-SYN/ACK retransmits to break down retransmissions in SYN, fast/timeout retransmits"
      },
      {
       "expr": "rate(node_netstat_Tcp_RetransSegs{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "RetransSegs - Segments retransmitted - that is, the number of TCP segments transmitted containing one or more previously transmitted octets"
      },
      {
       "expr": "rate(node_netstat_Tcp_InErrs{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "InErrs - Segments received in error (e.g., bad TCP checksums)"
      }
     ]
    },
    {
     "title": "TCP Connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 690 },
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT"
      },
      {
       "expr": "node_netstat_Tcp_MaxConn{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "MaxConn - Limit on the total number of TCP connections the entity can support (Dinamic is \"-1\")"
      }
     ]
    },
    {
     "title": "TCP SynCookie",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 690 },
     "targets": [
      {
       "expr": "rate(node_netstat_TcpExt_SyncookiesFailed{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "SyncookiesFailed - Invalid SYN cookies received"
      },
      {
       "expr": "rate(node_netstat_TcpExt_SyncookiesRecv{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "SyncookiesRecv - SYN cookies received"
      },
      {
       "expr": "rate(node_netstat_TcpExt_SyncookiesSent{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "SyncookiesSent - SYN cookies sent"
      }
     ]
    },
    {
     "title": "TCP Direct Transition",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 700 },
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_ActiveOpens{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "ActiveOpens - TCP connections that have made a direct transition to the SYN-SENT state from the CLOSED state"
      },
      {
       "expr": "rate(node_netstat_Tcp_PassiveOpens{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "PassiveOpens - TCP connections that have made a direct transition to the SYN-RCVD state from the LISTEN state"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 161 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Exporter Scrape Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 672 },
     "targets": [
      {
       "expr": "node_scrape_collector_duration_seconds{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "{{collector}} - Scrape duration"
      }
     ]
    },
    {
     "title": "Node Exporter Scrape",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 672 },
     "targets": [
      {
       "expr": "node_scrape_collector_success{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "{{collector}} - Scrape success"
      },
      {
       "expr": "node_textfile_scrape_error{asserts_env=~\"$env\",asserts_site=~\"$site\",instance=~\"$node.*\",job=\"$job\"}",
       "legendFormat": "{{collector}} - Scrape textfile error (1 = true)"
      }
     ]
    }
   ]
  }
 ]
}